### ISSUE TITLE
Move to JuliaLangSlack

### ISSUE THREAD

**Issue by logankilpatrick** [malmaud/slackinvite#3]
Hey Jon, I just made a JuliaLangSlack Org so that we can house the projects for Slack under one roof. I wanted to do this in case one of us ever moves on, someone else can pick up the torch on these projects! I added you as an admin there.

**Comment by logankilpatrick** [comment]
Hey @malmaud the cert for the invite page is down. Also, can you transfer this repo to the JuliaLangSlack org when you get a chance? Thanks!

**Comment by malmaud** [comment]
Done
